### ISSUE TITLE
Builds Not Working (1.6.1)

### ISSUE THREAD

**Issue by ZorroTrackerDev** [almoghamdani/audify#16] opened 2021-05-28 16:23 UTC
Okay so the build crashed on master, and by looking the travis builds, my first guess would because of artifact caching between builds, and that we indeed need the latest version and not the LTS one

_Originally posted by @ShinySaana in https://github.com/almoghamdani/audify/issues/15#issuecomment-850396333_

**Comment by almoghamdani** [comment] 2021-05-28 16:31
I already fixed the issue that caused the failure in the builds on master, it was caused by an older version of node-abi that didn't include support for Node.js 16.0.0 (I fixed it by updating all packages: [03ceda84](https://github.com/almoghamdani/audify/commit/48199892504b801f7939455590d7f61f03ceda84))
At the moment I can't release a new version because I ran out of monthly credits in TravisCI :( so I'm waiting for next month (which is in a few days) to release it. I removed v1.6.1 from npm, and I'll release v1.6.2 when possible.
I'll close this when fixed on v1.6.2

@ShinySaana FYI

**Comment by ShinySaana** [comment] 2021-05-28 16:32
Thanks for tagging

**Comment by ShinySaana** [comment] 2021-05-28 16:32
Thanks for tagging and resolving this as quickly as you did

**Comment by almoghamdani** [comment] 2021-05-28 16:48
> On another note, I can look at your existing travis-ci and migrate it to github actions, which has (afaik) no limitations on public repositories, if you would like

I'm currently exploring the idea of moving to GitHub Actions, but the lack of native support (without external workers) for armv7/aarch64 which TravisCI supports (armv7 with a workaround :D) is holding me back for now, but I'm testing the idea of using https://github.com/uraimo/run-on-arch-action as a workaround in order to build on arm.
Thanks for the suggestion anyway :smile:

**Comment by ShinySaana** [comment] 2021-05-28 17:25
Got you!

**Comment by almoghamdani** [comment] 2021-06-04 14:17
Fixed on v1.6.3. (prebuilt for Electron v14.0.0 was removed because node-abi doesn't support it yet - it's in initial beta)

**Closed by almoghamdani** 2021-06-04 14:17 UTC
